deploy

diff --git a/sf-deploy b/sf-deploy
--- a/sf-deploy
+++ b/sf-deploy
@@ -6,7 +6,7 @@
 # USAGE
 #
 #     sf-deploy                     # watch & deploy changed files and files in git-index (or full build-deploy-publish if no files are changed)
-#     sf-deploy -o ALIAS            # deploy to ALIAS org [default: b2bdev2]
+#     sf-deploy -o ALIAS            # deploy to ALIAS org
 #
 #     sf-deploy -x                  # explicitly build, deploy and publish
 #     sf-deploy -i                  # explicitly deploy changed files
@@ -18,12 +18,22 @@ yesno() {
   [[ $response == "n" || $response == "N" ]] && exit 1
 }
 
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
+
 [ -z "${SF_ORG_NAME}" ] && echo -e >&2 "\n $(tput setaf 0)environment variable 'SF_ORG_NAME' is missing$(tput sgr 0)" && exit 1
 orgname="${SF_ORG_NAME}"
-
-org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org"')
-[ -z "${org}" ] && echo -e >&2 "\n $(tput setaf 1)org-alias is missing$(tput sgr 0)\n\n     $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)" && exit 1
-
+org=""
 appfolder="force-app"
 result=$(mktemp)
 all=false
@@ -52,6 +62,7 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+setTargetOrg
 
 showresult() {
   cat ${result} | sed 1,2d | perl -pe "s/(Component Failures \[\d+\])$/ $(tput setaf 1)\1$(tput sgr 0)/" | cut -c -$(tput cols)
