deploy

diff --git a/sf-deploy b/sf-deploy
--- a/sf-deploy
+++ b/sf-deploy
@@ -1,13 +1,15 @@
 #!/usr/bin/env bash
 
 #
-# Build, deploy and publish a project to an Org
+# Build-deploy-publish a project or single files to an Salesforce Org
 #
 # USAGE
 #
-#     sf-deploy                     # deploy files in git staging area in watch mode (or full build, deploy & publish on empty git index)
-#     sf-deploy -x                  # build, deploy and publish explicitly
+#     sf-deploy                     # watch & deploy changed files and files in git-index (or full build-deploy-publish if no files are changed)
 #     sf-deploy -o ALIAS            # deploy to ALIAS org [default: b2bdev2]
+#
+#     sf-deploy -x                  # explicitly build, deploy and publish
+#     sf-deploy -i                  # explicitly deploy changed files
 #
 
 yesno() {
@@ -17,12 +19,15 @@ yesno() {
 }
 
 [ -z "${SF_ORG_NAME}" ] && echo -e >&2 "\n $(tput setaf 0)environment variable 'SF_ORG_NAME' is missing$(tput sgr 0)" && exit 1
-
 orgname="${SF_ORG_NAME}"
-org="b2bdev2"
+
+org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org"')
+[ -z "${org}" ] && echo -e >&2 "\n $(tput setaf 1)org-alias is missing$(tput sgr 0)" && exit 1
+
 appfolder="force-app"
 result=$(mktemp)
 all=false
+index=false
 
 while [ $# -gt 0 ]; do
   case $1 in
@@ -32,6 +37,9 @@ while [ $# -gt 0 ]; do
       ;;
     -x)
       all=true
+      ;;
+    -i)
+      index=true
       ;;
     -h|--help)
       cat $0 | sed -n '/^#/p' | sed '/^##/d' | sed 1d | sed 's/^#/ /g' \
@@ -70,7 +78,7 @@ deployAll() {
 }
 
 
-if [[ $(git diff --name-only | wc -l | tr -d ' ') == 0 || $all == true ]]; then
+if [[ $(git diff HEAD --name-only | wc -l | tr -d ' ') == 0 && $index == false || $all == true ]]; then
   yesno " Build, Deploy and Publish to $(tput setaf 1)${org}$(tput sgr0) ?"
   deployAll
 else
diff --git a/sf-deploy-index b/sf-deploy-index
--- a/sf-deploy-index
+++ b/sf-deploy-index
@@ -1,24 +1,29 @@
 #!/usr/bin/env bash
 
-# helper script for sf-deploy
+#
+# helper script to be called by 'sf-deploy'
+#
 
 
-org=${1:b2bdv2}
+[ -z "$1" ] && echo >&2 "Org Alias required!" && exit 1
+org=$1
+publish=false
 
 mapOption() {
   option=''
   case $1 in
     staticresources*)
-      option="StaticResource:"
-      option="${option}$(echo $1 | perl -pe 's#staticresources/(.+?)\..+#\1#')"
+      option="StaticResource:$(echo $1 | perl -pe 's#staticresources/(.+?)\..+#\1#')"
       ;;
     lwc*)
-      option="LightningComponentBundle:"
-      option="${option}$(echo $1 | perl -pe 's#lwc/(.+?)/.+#\1#')"
+      option="LightningComponentBundle:$(echo $1 | perl -pe 's#lwc/(.+?)/.+#\1#')"
       ;;
     classes*)
-      option="ApexClass:"
-      option="${option}$(echo $1 | perl -pe 's#classes/(.+?)\..+#\1#')"
+      option="ApexClass:$(echo $1 | perl -pe 's#classes/(.+?)\..+#\1#')"
+      ;;
+    experiences*)
+      option="ExperienceBundle:$(echo $1 | perl -pe 's#experiences/(.+?)/.+#\1#')"
+      publish=true
       ;;
   esac
   echo ${option}
@@ -28,18 +33,22 @@ declare -a options
 while read f; do
   path=$(echo $f | perl -pe 's#force-app/main/default/([^/]*)#\1#')
   options=(${options[@]} "$(mapOption "${path}")")
-done < <(git diff --name-only)
+done < <(git diff HEAD --name-only)
 
 uniq_options=($(for option in "${options[@]}"; do echo "${option}"; done | sort -u))
 
 if [[ ${#uniq_options[@]} == 0 ]]; then
   echo -e " $(tput setaf 1)git index is empty, nothing to deploy$(tput sgr0) ...\n"
 else
-  echo -e " $(tput setaf 2)found ${#uniq_options[@]} file(s) to deploy$(tput sgr0) ...\n"
+  echo -e " $(tput setaf 2)found ${#options[@]} file$([[ ! ${#options[@]} -eq 1 ]] && echo "s") and ${#uniq_options[@]} metadata entit$([[ ${#uniq_options[@]} -eq 1 ]] && echo "y" || echo "ies") to deploy$(tput sgr0) ...\n"
   opts=''
   for p in ${uniq_options[@]}; do
     opts="${opts} -m ${p}"
   done
   sf project deploy start${opts} -o ${org}
+  if [[ $publish == true ]]; then
+    name=$(sf data query -o ${org} -q "SELECT Name FROM Site WHERE UrlPathPrefix=''" --json | jq -r '.result.records[].Name')
+    sf community publish -n ${name} -o ${org} >/dev/null
+  fi
   echo -e " $(tput setaf 2)waiting for changes$(tput sgr0) ...\n"
 fi
