remove hardcoded default org

diff --git a/sf-data b/sf-data
--- a/sf-data
+++ b/sf-data
@@ -5,7 +5,7 @@
 #
 # USAGE
 #
-#     sf-data -o ALIAS                  # query from ALIAS org [default: b2bdev2]
+#     sf-data -o ALIAS                  # query from ALIAS org
 #     sf-data -d DIR                    # save data in DIR folder [default: .data]
 #     sf-data                           # query all data from default org and save in default folder
 #
@@ -26,7 +26,20 @@ yesno() {
   [[ $response == "n" || $response == "N" ]] && exit 1
 }
 
-org="b2bdev2"
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
+
+org=""
 target=".data"
 object=""
 visidata=false
@@ -70,6 +83,7 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+setTargetOrg
 
 if [ $refresh == true ]; then
   object=$(fd . ${target} -e csv -x echo {/.} | tr '\n' ',')
diff --git a/sf-log b/sf-log
--- a/sf-log
+++ b/sf-log
@@ -5,10 +5,23 @@
 #
 # USAGE
 #
-#     sf-log -o ALIAS                 # enable trace logging for 24 hours on ALIAS org [default: b2bdev2]
+#     sf-log -o ALIAS                 # enable trace logging for 24 hours on ALIAS org
 #
 
-org='b2bdev2'
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
+
+org=""
 
 while [ $# -gt 0 ]; do
   case $1 in
@@ -27,6 +40,7 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+setTargetOrg
 
 now=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
 exp=`date -v+24H -u +"%Y-%m-%dT%H:%M:%SZ"`
diff --git a/sf-metadata b/sf-metadata
--- a/sf-metadata
+++ b/sf-metadata
@@ -11,7 +11,20 @@
 #    sf-metadata -x                        # retrieve metadata based on manifest/package.xml
 #
 
-org="b2bdev2"
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
+
+org=""
 name=""
 names_list=$(mktemp)
 
@@ -46,6 +59,7 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+setTargetOrg
 
 if [[ $name == "" ]]; then
   name="all"
diff --git a/sf-tooldata b/sf-tooldata
--- a/sf-tooldata
+++ b/sf-tooldata
@@ -5,7 +5,7 @@
 #
 # USAGE
 #
-#     sf-tooldata -o ALIAS                  # query from ALIAS org [default: b2bdev2]
+#     sf-tooldata -o ALIAS                  # query from ALIAS org
 #     sf-tooldata -d DIR                    # save data in DIR folder [default: .tooldata]
 #     sf-tooldata                           # query all data from default org and save in default folder
 #
@@ -19,7 +19,20 @@ yesno() {
   [[ $response == "n" || $response == "N" ]] && exit 1
 }
 
-org="b2bdev2"
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
+
+org=""
 target=".tooldata"
 object="all"
 visidata=false
@@ -59,6 +72,7 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+setTargetOrg
 
 objects=$(echo ${object} | perl -pe "s/,/, /g" | perl -pe "s/(\w+)/$(tput setaf 4)\1$(tput sgr0)/g")
 yesno " Fetch ${objects} data of $(tput setaf 2)Tooling API$(tput sgr0) from $(tput setaf 1)${org}$(tput sgr0) ?"
diff --git a/sf-validate b/sf-validate
--- a/sf-validate
+++ b/sf-validate
@@ -5,7 +5,7 @@
 #
 # USAGE
 #
-#     sf-validate -o ALIAS         # validate deployment with unit tests on ALIAS org [default: b2bdev2]
+#     sf-validate -o ALIAS         # validate deployment with unit tests on ALIAS org
 #     sf-validate -n               # validate deployment without unit tests
 #
 
@@ -15,10 +15,20 @@ yesno() {
   [[ $response == "n" || $response == "N" ]] && exit 1
 }
 
-[ -z "${SF_ORG_NAME}" ] && echo -e >&2 "\n $(tput setaf 0)environment variable 'SF_ORG_NAME' is missing$(tput sgr 0)" && exit 1
+setTargetOrg() {
+  if [[ -z "$org" ]]; then
+    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
+  fi
+  if [[ -z "$org" ]]; then
+    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
+    exit 1
+  fi
+}
 
-orgname="${SF_ORG_NAME}"
-org="b2bdev2"
+org=""
 unittests=true
 result=$(mktemp)
 
@@ -46,6 +56,7 @@ done
 showresult() {
   tail -n 9 ${result} | perl -pe "s/(Successfully validated the deployment)/ $(tput setaf 2)\1$(tput sgr 0)/" | cut -c -$(tput cols)
   deployid=$(cat ${result} | grep "Deploy ID" | perl -pe 's/Deploy ID: (.*)/\1/')
+  orgname=$(sf data query -q "SELECT Domain FROM Domain WHERE HttpsOption = 'CommunityAlt'" --json | jq -r '.result.records[].Domain' | perl -pe 's/(.+)--.+/\1/')
   deployurl="https://${orgname}--${1}.sandbox.lightning.force.com/lightning/setup/DeployStatus/page?address=/changemgmt/monitorDeploymentsDetails.apexp?asyncId=${deployid}"
   echo -e "\n $(tput setaf 2)Deployment Status:$(tput sgr0)\n  ${deployurl}"
 }
