deploy

diff --git a/sf-deploy b/sf-deploy
--- a/sf-deploy
+++ b/sf-deploy
@@ -13,8 +13,12 @@ yesno() {
   [[ $response == "n" || $response == "N" ]] && exit 1
 }
 
+[ -z "${SF_ORG_NAME}" ] && echo -e >&2 "\n $(tput setaf 0)environment variable 'SF_ORG_NAME' is missing$(tput sgr 0)" && exit 1
+
+orgname="${SF_ORG_NAME}"
 org="b2bdev2"
 validate="false"
+result=$(mktemp)
 
 while [ $# -gt 0 ]; do
   case $1 in
@@ -37,21 +41,24 @@ while [ $# -gt 0 ]; do
   shift
 done
 
+showresult() {
+  cat ${result} | sed 1,2d | perl -pe "s/(Component Failures \[\d+\])$/$(tput setaf 1)\1$(tput sgr 0)/" | cut -c -$(tput cols)
+  deployid=$(cat ${result} | grep "Deploy ID" | perl -pe 's/Deploy ID: (.*)/\1/')
+  deployurl="https://${orgname}--${1}.sandbox.lightning.force.com/lightning/setup/DeployStatus/page?address=/changemgmt/monitorDeploymentsDetails.apexp?asyncId=${deployid}"
+  echo -e "\n $(tput setaf 2)Deployment Status:$(tput sgr0)\n   ${deployurl}"
+}
+
 if [[ $validate == "true" ]]; then
   yesno " Verify Deployment on $(tput setaf 1)${org}$(tput sgr0) ?"
   echo -e "\n $(tput setaf 2)Verify Deployment$(tput sgr0) ..."
-  sfdx project deploy validate -x manifest/package.xml -l RunSpecifiedTests -t `cat scripts/test/unit-test-list.txt | sed s/,$// | awk '{ printf(" -t %s", $0) }'` -o ${org} > result.tmp
-  cat result.tmp | cut -c -$(tput cols)
-  deployid=$(cat result.tmp | grep "Deploy ID" | perl -pe 's/Deploy ID: (.*)/\1/')
-  deployurl="https://mediverse--b2bdev1.sandbox.lightning.force.com/lightning/setup/DeployStatus/page?address=/changemgmt/monitorDeploymentsDetails.apexp?asyncId=${deployid}"
-  echo -e "˜n $(tput setaf 1)Deployment Status:$(tput sgr0) ${deployurl}"
-  rm result.tmp
+  sfdx project deploy validate -x manifest/package.xml -l RunSpecifiedTests -t `cat scripts/test/unit-test-list.txt | sed s/,$// | awk '{ printf(" -t %s", $0) }'` -o ${org} > ${result}
+  showresult ${org}
 else
   yesno " Deploy to $(tput setaf 1)${org}$(tput sgr0) ?"
   echo -e "\n $(tput setaf 2)Build Frontend CSS$(tput sgr0) ..."
   (cd frontend && npm run frontend:build >/dev/null)
   echo " $(tput setaf 2)Deploy$(tput sgr0) ..."
-  sfdx project deploy start -x manifest/package.xml -o ${org} > /dev/null
+  sfdx project deploy start -x manifest/package.xml --concise -o ${org} > ${result}
   if [[ $? == 0 ]]; then
     echo " $(tput setaf 2)Publish$(tput sgr0) ..."
     name=$(sfdx data query -o ${org} -q "SELECT Name FROM Site WHERE UrlPathPrefix=''" --json | jq -r '.result.records[].Name')
@@ -60,7 +67,6 @@ else
     domain=$(sfdx data query -o ${org} -q "SELECT Domain FROM Domain WHERE HttpsOption='CommunityAlt'" --json | jq -r '.result.records[].Domain')
     echo " $(tput setaf 2)Finish$(tput sgr0): ${domain}"
   else
-    echo " $(tput setaf 1)Deployment Error$(tput sgr0)"
+    showresult ${org}
   fi
 fi
-
